#!/bin/bash

set -eu

# ================================================================
# DAE eBPF Kernel Config — FriendlyWRT RK3576 (kernel 6.1)
#
# Covers all 16 official daeuniverse/dae kernel requirements.
# Includes two additional fixes for kernel 6.1 Kconfig structure:
#   1. CONFIG_DEBUG_INFO_NONE explicitly disabled (prevents BTF
#      being silently nullified by the kernel 6.1 choice block).
#   2. CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT=y set explicitly
#      (kernel 6.1 requires an explicit DWARF format selection).
#
# Size optimisation for RK3576 boot partition limit:
#   CONFIG_DEBUG_INFO_SPLIT=y — moves DWARF into separate .dwo
#   sidecar files at compile time; they are NOT included in the
#   final kernel Image/Image.gz. BTF is still generated by pahole
#   from the .dwo files and embedded in the kernel normally.
#   Expected savings: 4–10 MB from the final kernel.img.
#
# All options are forced =y (built into kernel).
# DAE officially permits =m for NET_SCH_INGRESS and NET_CLS_BPF,
# but =y eliminates module load-order dependencies.
# ================================================================

CONFIGS=(
    # --- eBPF core & JIT ---
    "CONFIG_BPF=y"
    "CONFIG_BPF_SYSCALL=y"
    "CONFIG_BPF_JIT=y"
    "CONFIG_BPF_JIT_ALWAYS_ON=y"           # no interpreter fallback on ARM64

    # --- Cgroup + eBPF (dae socket redirection requires this) ---
    "CONFIG_CGROUPS=y"
    "CONFIG_CGROUP_BPF=y"

    # --- Kprobes & BPF tracing ---
    "CONFIG_KPROBES=y"
    "CONFIG_KPROBE_EVENTS=y"
    "CONFIG_BPF_EVENTS=y"

    # --- TC / network eBPF hooks ---
    # dae minimum is =m; using =y (built-in) is strictly stronger.
    "CONFIG_NET_INGRESS=y"
    "CONFIG_NET_EGRESS=y"
    "CONFIG_NET_SCH_INGRESS=y"
    "CONFIG_NET_CLS_BPF=y"
    "CONFIG_NET_CLS_ACT=y"
    "CONFIG_BPF_STREAM_PARSER=y"

    # --- BTF / debug info (kernel 6.1 canonical form) ---
    # Step order in DISABLE_CONFIGS below ensures DEBUG_INFO_NONE
    # is removed BEFORE these lines are appended.
    #
    # DEBUG_INFO=y            : master switch (also legacy compat)
    # DWARF_TOOLCHAIN_DEFAULT : explicit DWARF format for 6.1 choice block
    # DEBUG_INFO_SPLIT        : DWARF in .dwo files, NOT in kernel Image
    # DEBUG_INFO_BTF          : BTF generated from DWARF, embedded in kernel
    "CONFIG_DEBUG_INFO=y"
    "CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT=y"
    "CONFIG_DEBUG_INFO_SPLIT=y"
    "CONFIG_DEBUG_INFO_BTF=y"

    # --- Runtime config inspection ---
    # Verify with: zcat /proc/config.gz | grep -E "BPF|BTF|DEBUG_INFO"
    "CONFIG_IKCONFIG=y"
    "CONFIG_IKCONFIG_PROC=y"
)

# ----------------------------------------------------------------
# Options to disable.
#
# ORDER IS CRITICAL:
#   CONFIG_DEBUG_INFO_NONE must be the first entry.
#   In kernel 6.1 the debug-info format is a Kconfig "choice" block.
#   If NONE appears anywhere in the defconfig it wins the choice and
#   silently overrides DEBUG_INFO=y and DEBUG_INFO_BTF=y regardless
#   of append order. Disabling it before injecting the CONFIGS array
#   prevents this race.
# ----------------------------------------------------------------
DISABLE_CONFIGS=(
    "CONFIG_DEBUG_INFO_NONE"             # FIRST — blocks BTF if set
    "CONFIG_DEBUG_INFO_REDUCED"          # official dae requirement
    "CONFIG_DEBUG_INFO_DWARF5"           # explicit format control (6.1)
    "CONFIG_DEBUG_INFO_DWARF4"           # explicit format control (6.1)
    "CONFIG_DEBUG_INFO_COMPRESSED_ZLIB"  # incompatible with SPLIT
    "CONFIG_DEBUG_INFO_COMPRESSED_ZSTD"  # incompatible with SPLIT
)

# ================================================================

source .current_config.mk

KCFG=kernel/arch/arm64/configs/$(awk '{print $1}' <<< "$TARGET_KERNEL_CONFIG")

echo "Using kernel config: $KCFG"
echo

# ---- Step 1: disable blocking options -------------------------
echo "[1/2] Disabling incompatible options..."
for KEY in "${DISABLE_CONFIGS[@]}"; do
    sed -i \
        -e "/^${KEY}=.*/d" \
        -e "/^# ${KEY} is not set$/d" \
        "$KCFG"
    echo "  # ${KEY} is not set"
    echo "# ${KEY} is not set" >> "$KCFG"
done

echo
# ---- Step 2: inject required options --------------------------
echo "[2/2] Injecting DAE eBPF options..."
for CONFIG in "${CONFIGS[@]}"; do
    KEY="${CONFIG%%=*}"
    # Remove both "KEY=val" and "# KEY is not set" forms
    sed -i \
        -e "/^${KEY}=.*/d" \
        -e "/^# ${KEY} is not set$/d" \
        "$KCFG"
    echo "  $CONFIG"
    echo "$CONFIG" >> "$KCFG"
done

echo
echo "=================================================="
echo " DAE eBPF kernel config applied successfully"
echo "  Config file : $KCFG"
echo "  dae requirements  : 16/16 covered"
echo "  Kernel 6.1 fixes  : DEBUG_INFO_NONE disabled"
echo "                      DWARF_TOOLCHAIN_DEFAULT set"
echo "  Size optimisation : DEBUG_INFO_SPLIT=y"
echo "=================================================="
